apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: fortune
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortune
  template:
    metadata:
      labels:
        app: fortune
    spec:
      containers:
      - name: html-generator
        image: uriahas/fortune:args
        env:
        - name: INTERVAL
          valueFrom:
            configMapKeyRef:
              name: fortune-config
              key: sleep-interval
        args: ["$(INTERVAL)"]
        volumeMounts:
        - name: html
          mountPath: /var/htdocs
      - name: web-server
        image: nginx:alpine
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
          readOnly: true
        - name: config
          mountPath: /etc/nginx/conf.d/gzip.conf
          subPath: gzip.conf
          readOnly: true
        - name: certs
          mountPath: /etc/nginx/certs/
          readOnly: true
        ports:
        - containerPort: 80
          protocol: TCP
      volumes:
      - name: html
        emptyDir: {}
      - name: config
        configMap:
          name: fortune-config
          defaultMode: 0660
          items:
          - key: nginx.conf
            path: gzip.conf
      - name: certs
        secret:
          secretName: fortune-https