apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: fortune
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortune
  template:
    metadata:
      labels:
        app: fortune
    spec:
      containers:
      - name: fortune
        image: uriahas/fortune