apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  storageClassName: nfs-client
  resources:
    requests:
      storage: 100Mi
  accessModes:
  - ReadWriteOnce